# Generated by Django 3.1.1 on 2020-09-10 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('spotify_id', models.CharField(max_length=22)),
                ('cancion_name', models.CharField(max_length=100)),
                ('album_id', models.CharField(max_length=22)),
                ('release_date', models.DateField()),
                ('duration_ms', models.IntegerField()),
                ('letra_url', models.CharField(max_length=100)),
                ('letra_completa', models.TextField()),
            ],
        ),
    ]
