# Generated by Django 3.1.1 on 2020-09-10 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melomaniapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('spotify_id', models.CharField(max_length=22)),
                ('album_name', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=100)),
                ('artista_id', models.CharField(max_length=22)),
            ],
        ),
    ]
