# Generated by Django 3.1.1 on 2020-09-10 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melomaniapp', '0002_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='spotify_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='spotify_id',
            field=models.CharField(max_length=30),
        ),
    ]
