# Generated by Django 3.1.1 on 2020-09-10 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('melomaniapp', '0003_auto_20200909_2218'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cancion',
            table='',
        ),
    ]
